import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  DynamicContextProvider,
  EthereumWalletConnectors,
} from "../lib/dynamic"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ref3R",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: process.env.DYNAMIC_PROJECT_ID || '',
            walletConnectors: [EthereumWalletConnectors]
          }}
        >
          {children}
        </DynamicContextProvider>
      </body>
    </html>
  );
}
